# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reading', '0007_fillup_fillupque_matching_mcq_mcqques'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='Reading Test', max_length=100)),
                ('ques1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Reading1', to='reading.passageMain')),
                ('ques2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Reading2', to='reading.passageMain')),
                ('ques3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Reading3', to='reading.passageMain')),
            ],
        ),
    ]
