# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-21 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
        ('questionpaper', '0002_listeningtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='Writing Test', max_length=100)),
                ('ques1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Listening1', to='writing.Writing')),
                ('ques2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Listening2', to='writing.Writing')),
            ],
        ),
    ]
