# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0004_writinganswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='writinganswer',
            name='student',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
