# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-23 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0005_writinganswer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writinganswer',
            name='ques1',
        ),
        migrations.AddField(
            model_name='writinganswer',
            name='ans',
            field=models.TextField(default='Nothing Wriiten by the Student', max_length=1000000),
        ),
        migrations.AddField(
            model_name='writinganswer',
            name='ques',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
