# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-24 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0008_auto_20190224_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_id0',
            field=models.IntegerField(null=True),
        ),
    ]
