# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0010_auto_20190224_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinganswer',
            name='test_name',
            field=models.CharField(default='Reading Test', max_length=100),
        ),
    ]
