# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-24 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0011_auto_20190224_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinganswer',
            name='mcq0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mcq_id',
            field=models.IntegerField(null=True),
        ),
    ]
