# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0013_auto_20190224_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinganswer',
            old_name='fillup_id',
            new_name='fillup_id0',
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_id1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_id2',
            field=models.IntegerField(null=True),
        ),
    ]
