# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0014_auto_20190224_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='Reading Test', max_length=100)),
                ('map_id0', models.IntegerField(null=True)),
                ('map0', models.CharField(max_length=10, null=True)),
                ('map_id1', models.IntegerField(null=True)),
                ('map1', models.CharField(max_length=10, null=True)),
                ('map_id2', models.IntegerField(null=True)),
                ('map2', models.CharField(max_length=10, null=True)),
                ('map_id3', models.IntegerField(null=True)),
                ('map3', models.CharField(max_length=10, null=True)),
                ('map_id4', models.IntegerField(null=True)),
                ('map4', models.CharField(max_length=10, null=True)),
                ('map_id5', models.IntegerField(null=True)),
                ('map5', models.CharField(max_length=10, null=True)),
                ('sum_id', models.IntegerField(null=True)),
                ('sum0', models.CharField(max_length=100, null=True)),
                ('sum1', models.CharField(max_length=100, null=True)),
                ('sum2', models.CharField(max_length=100, null=True)),
                ('sum3', models.CharField(max_length=100, null=True)),
                ('sum4', models.CharField(max_length=100, null=True)),
                ('sum5', models.CharField(max_length=100, null=True)),
                ('mcq_id', models.IntegerField(null=True)),
                ('mcq0', models.CharField(max_length=100, null=True)),
                ('fillup_id0', models.IntegerField(null=True)),
                ('fillup0', models.CharField(max_length=100, null=True)),
                ('fillup_id1', models.IntegerField(null=True)),
                ('fillup1', models.CharField(max_length=100, null=True)),
                ('fillup_id2', models.IntegerField(null=True)),
                ('fillup2', models.CharField(max_length=100, null=True)),
                ('fillup_id3', models.IntegerField(null=True)),
                ('fillup3', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
