# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-28 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0016_auto_20190228_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listeninganswer',
            old_name='mat_id0',
            new_name='mat_id',
        ),
        migrations.RemoveField(
            model_name='listeninganswer',
            name='mat_id1',
        ),
        migrations.RemoveField(
            model_name='listeninganswer',
            name='mat_id2',
        ),
        migrations.RemoveField(
            model_name='listeninganswer',
            name='mat_id3',
        ),
        migrations.RemoveField(
            model_name='listeninganswer',
            name='mat_id4',
        ),
        migrations.RemoveField(
            model_name='listeninganswer',
            name='mat_id5',
        ),
    ]
