# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-28 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0017_auto_20190228_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninganswer',
            name='student',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='student',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
