# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0018_auto_20190228_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writinganswer',
            old_name='ans',
            new_name='ans1',
        ),
        migrations.RenameField(
            model_name='writinganswer',
            old_name='ques',
            new_name='ques1',
        ),
        migrations.AddField(
            model_name='writinganswer',
            name='ans2',
            field=models.TextField(default='Nothing Wriiten by the Student', max_length=1000000),
        ),
        migrations.AddField(
            model_name='writinganswer',
            name='ques2',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
