# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-17 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0020_auto_20190317_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_idb0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_idb1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_idb2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillupb0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillupb1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillupb2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mat_idb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matb0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matb1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matb2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matb3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matb4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matb5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mcq_idb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mcqb0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sum_idb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumb0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumb1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumb2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumb3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumb4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumb5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idb0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idb1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idb2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idb3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idb4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idb5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnb0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnb1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnb2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnb3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnb4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnb5',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
