# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-17 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0021_auto_20190317_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_idc0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_idc1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_idc2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_idd0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_idd1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillup_idd2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillupc0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillupc1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillupc2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillupd0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillupd1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='fillupd2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mat_idc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mat_idd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matc0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matc1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matc2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matc3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matc4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matc5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matd0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matd1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matd2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matd3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matd4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='matd5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mcq_idc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mcq_idd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mcqc0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='mcqd0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sum_idc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sum_idd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumc0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumc1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumc2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumc3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumc4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumc5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumd0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumd1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumd2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumd3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumd4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='sumd5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idc0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idc1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idc2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idc3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idc4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idc5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idd0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idd1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idd2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idd3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idd4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysn_idd5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnc0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnc1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnc2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnc3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnc4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnc5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnd0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnd1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnd2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnd3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnd4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='ysnd5',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
