# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-18 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0022_auto_20190317_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idb0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idb1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idb2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idc0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idc1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idc2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idd0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idd1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idd2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupb0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupb1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupb2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupc0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupc1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupc2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupd0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupd1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupd2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idb0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idb1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idb2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idb3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idb4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idb5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idc0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idc1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idc2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idc3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idc4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idc5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idd0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idd1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idd2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idd3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idd4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='map_idd5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapb0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapb1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapb2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapb3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapb4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapb5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapc0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapc1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapc2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapc3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapc4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapc5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapd0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapd1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapd2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapd3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapd4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mapd5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mat_idb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mat_idc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mat_idd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matb0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matb1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matb2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matb3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matb4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matb5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matc0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matc1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matc2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matc3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matc4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matc5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matd0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matd1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matd2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matd3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matd4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='matd5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_idb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_idc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_idd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcqb0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcqc0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcqd0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sum_idb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sum_idc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sum_idd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumb0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumb1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumb2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumb3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumb4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumb5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumc0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumc1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumc2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumc3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumc4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumc5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumd0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumd1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumd2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumd3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumd4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='sumd5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
