# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passageMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Name', models.CharField(default='Passage', max_length=50)),
                ('passage', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='yesNoNotGiven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Name', models.CharField(default='ynnQuestion', max_length=50)),
                ('Instruction', models.TextField(default='your instructions', max_length=200)),
                ('passage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passageynn', to='reading.passageMain')),
            ],
        ),
        migrations.CreateModel(
            name='yesNoNotGivenQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(default='Your questions', max_length=100)),
                ('linked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked', to='reading.yesNoNotGiven')),
            ],
        ),
    ]
