# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagemain',
            name='passage',
            field=models.TextField(max_length=1000000),
        ),
    ]
