# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-18 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_auto_20190218_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagemain',
            name='Instruction',
            field=models.TextField(default='instructions', max_length=200),
        ),
    ]
