# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_passagemain_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagemain',
            name='Question_Name',
            field=models.CharField(default=' Reading Passage', max_length=50),
        ),
    ]
