# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_auto_20190218_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Name', models.CharField(default='summary Question', max_length=50)),
                ('Instruction', models.TextField(default='your instructions', max_length=2000)),
                ('part1', models.CharField(max_length=100, null=True)),
                ('part2', models.CharField(max_length=100, null=True)),
                ('part3', models.CharField(blank=True, max_length=100, null=True)),
                ('part4', models.CharField(blank=True, max_length=100, null=True)),
                ('part5', models.CharField(blank=True, max_length=100, null=True)),
                ('part6', models.CharField(blank=True, max_length=100, null=True)),
                ('part7', models.CharField(blank=True, max_length=100, null=True)),
                ('passage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passagesumm', to='reading.passageMain')),
            ],
        ),
    ]
