# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190303_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=20, null=True),
        ),
    ]
