# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Organisation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
