# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-05 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
