# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(default='Mr x', max_length=100)),
                ('test_name', models.CharField(default='TEST X', max_length=100)),
            ],
        ),
    ]
