# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-15 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='status',
            field=models.CharField(default='Assigned', max_length=100),
        ),
    ]
