# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-17 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_assign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='test_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
