# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-17 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_assign_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='test_id',
        ),
    ]
