# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-21 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Name', models.CharField(default='Question', max_length=100)),
                ('timeInstruction', models.CharField(max_length=100)),
                ('Question', models.CharField(max_length=1000)),
                ('wordInstruction', models.CharField(max_length=100)),
                ('image_ques', models.ImageField(null=True, upload_to='picfolder/')),
            ],
        ),
    ]
