# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-21 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq',
            old_name='passage',
            new_name='audio',
        ),
    ]
